language: swift
osx_image: xcode11.2
git:
  submodules: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
before_install:
- swift package resolve
script:
- swift test
notifications:
  email:
    on_success: never
